typography_spectrum: 0.88652
color:
  brandColors:
    - '#7cad51'
    - '#106383'
    - '#517e3d'
    - '#dc4800'
    - '#702b01'
  brandStrength: 0
  lightness: 0
  saturation: 1
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.2204301
analytics:
  google: null
  facebook: null
  twitter: null
name: random4
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - id: 75f9b66b-4441-4edd-86f5-0d0fa71ec6a2
    url: 2016-03-06-75f9b66b-4441-4edd-86f5-0d0fa71ec6a2.html
    name: About
    type: content
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
